---
- hosts: mywebservers
  become: yes

  tasks:
      - name: update/install nginx
        apt:
            name: nginx
            state: latest
            update_cache: yes
      - name: copy html
        template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
      - name: restart nginx
        service: name=nginx state=restarted
        become: true 
        become_method: sudo
  handlers:
  - name: start nginx

    service: 
      name: nginx
      state: present
